
'------------------------------------------------------------------------------
' <auto-generated>
'    Este código se generó a partir de una plantilla.
'
'    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("ea6ed5c8-d43d-4e89-9c44-9c6432339550")>
#Region "Metadatos de relaciones en EDM"
<Assembly: EdmRelationshipAttribute("Modelo", "DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(SUCURSALES), "DETALLE_SUCURSAL_OFICINA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DETALLE_SUCURSAL_OFICINA), True)>
<Assembly: EdmRelationshipAttribute("Modelo", "DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(OFICINAS), "DETALLE_SUCURSAL_OFICINA", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DETALLE_SUCURSAL_OFICINA), True)>
<Assembly: EdmRelationshipAttribute("Modelo", "USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(DETALLE_SUCURSAL_OFICINA), "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(USUARIOS), True)>
<Assembly: EdmRelationshipAttribute("Modelo", "VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(DETALLE_SUCURSAL_OFICINA), "VENTANILLAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(VENTANILLAS), True)>
<Assembly: EdmRelationshipAttribute("Modelo", "PETICION_GESTIONES_FK1", "GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(GESTIONES), "PETICION_GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(PETICION_GESTIONES), True)>
<Assembly: EdmRelationshipAttribute("Modelo", "SUCURSALES_FK1", "MUNICIPIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(MUNICIPIOS), "SUCURSALES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(SUCURSALES), True)>
<Assembly: EdmRelationshipAttribute("Modelo", "DETALLE_USUARIOS_PERFILES", "USUARIOS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(USUARIOS), "PERFILES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(PERFILES))>
<Assembly: EdmRelationshipAttribute("Modelo", "DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(OFICINAS), "DETALLE_OFICINA_GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DETALLE_OFICINA_GESTIONES), True)>
<Assembly: EdmRelationshipAttribute("Modelo", "DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(GESTIONES), "DETALLE_OFICINA_GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DETALLE_OFICINA_GESTIONES), True)>
<Assembly: EdmRelationshipAttribute("Modelo", "GESTIONES_VENTANILLAS1", "DETALLE_OFICINA_GESTIONES", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(DETALLE_OFICINA_GESTIONES), "VENTANILLAS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(VENTANILLAS))>

#End Region

#Region "Contextos"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
Public Partial Class Entidades
    Inherits ObjectContext

    #Region "Constructores"

    ''' <summary>
    ''' Inicializa un nuevo objeto Entidades usando la cadena de conexión encontrada en la sección 'Entidades' del archivo de configuración de la aplicación.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=Entidades", "Entidades")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto Entidades.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "Entidades")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Inicializar un nuevo objeto Entidades.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "Entidades")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Métodos parciales"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "Propiedades de ObjectSet"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property DETALLE_SUCURSAL_OFICINA() As ObjectSet(Of DETALLE_SUCURSAL_OFICINA)
        Get
            If (_DETALLE_SUCURSAL_OFICINA Is Nothing) Then
                _DETALLE_SUCURSAL_OFICINA = MyBase.CreateObjectSet(Of DETALLE_SUCURSAL_OFICINA)("DETALLE_SUCURSAL_OFICINA")
            End If
            Return _DETALLE_SUCURSAL_OFICINA
        End Get
    End Property

    Private _DETALLE_SUCURSAL_OFICINA As ObjectSet(Of DETALLE_SUCURSAL_OFICINA)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property GESTIONES() As ObjectSet(Of GESTIONES)
        Get
            If (_GESTIONES Is Nothing) Then
                _GESTIONES = MyBase.CreateObjectSet(Of GESTIONES)("GESTIONES")
            End If
            Return _GESTIONES
        End Get
    End Property

    Private _GESTIONES As ObjectSet(Of GESTIONES)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property MUNICIPIOS() As ObjectSet(Of MUNICIPIOS)
        Get
            If (_MUNICIPIOS Is Nothing) Then
                _MUNICIPIOS = MyBase.CreateObjectSet(Of MUNICIPIOS)("MUNICIPIOS")
            End If
            Return _MUNICIPIOS
        End Get
    End Property

    Private _MUNICIPIOS As ObjectSet(Of MUNICIPIOS)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property OFICINAS() As ObjectSet(Of OFICINAS)
        Get
            If (_OFICINAS Is Nothing) Then
                _OFICINAS = MyBase.CreateObjectSet(Of OFICINAS)("OFICINAS")
            End If
            Return _OFICINAS
        End Get
    End Property

    Private _OFICINAS As ObjectSet(Of OFICINAS)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property PERFILES() As ObjectSet(Of PERFILES)
        Get
            If (_PERFILES Is Nothing) Then
                _PERFILES = MyBase.CreateObjectSet(Of PERFILES)("PERFILES")
            End If
            Return _PERFILES
        End Get
    End Property

    Private _PERFILES As ObjectSet(Of PERFILES)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property PETICION_GESTIONES() As ObjectSet(Of PETICION_GESTIONES)
        Get
            If (_PETICION_GESTIONES Is Nothing) Then
                _PETICION_GESTIONES = MyBase.CreateObjectSet(Of PETICION_GESTIONES)("PETICION_GESTIONES")
            End If
            Return _PETICION_GESTIONES
        End Get
    End Property

    Private _PETICION_GESTIONES As ObjectSet(Of PETICION_GESTIONES)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property SUCURSALES() As ObjectSet(Of SUCURSALES)
        Get
            If (_SUCURSALES Is Nothing) Then
                _SUCURSALES = MyBase.CreateObjectSet(Of SUCURSALES)("SUCURSALES")
            End If
            Return _SUCURSALES
        End Get
    End Property

    Private _SUCURSALES As ObjectSet(Of SUCURSALES)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property USUARIOS() As ObjectSet(Of USUARIOS)
        Get
            If (_USUARIOS Is Nothing) Then
                _USUARIOS = MyBase.CreateObjectSet(Of USUARIOS)("USUARIOS")
            End If
            Return _USUARIOS
        End Get
    End Property

    Private _USUARIOS As ObjectSet(Of USUARIOS)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property VENTANILLAS() As ObjectSet(Of VENTANILLAS)
        Get
            If (_VENTANILLAS Is Nothing) Then
                _VENTANILLAS = MyBase.CreateObjectSet(Of VENTANILLAS)("VENTANILLAS")
            End If
            Return _VENTANILLAS
        End Get
    End Property

    Private _VENTANILLAS As ObjectSet(Of VENTANILLAS)

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    Public ReadOnly Property DETALLE_OFICINA_GESTIONES() As ObjectSet(Of DETALLE_OFICINA_GESTIONES)
        Get
            If (_DETALLE_OFICINA_GESTIONES Is Nothing) Then
                _DETALLE_OFICINA_GESTIONES = MyBase.CreateObjectSet(Of DETALLE_OFICINA_GESTIONES)("DETALLE_OFICINA_GESTIONES")
            End If
            Return _DETALLE_OFICINA_GESTIONES
        End Get
    End Property

    Private _DETALLE_OFICINA_GESTIONES As ObjectSet(Of DETALLE_OFICINA_GESTIONES)

    #End Region

    #Region "Métodos AddTo"

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet DETALLE_SUCURSAL_OFICINA. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToDETALLE_SUCURSAL_OFICINA(ByVal dETALLE_SUCURSAL_OFICINA As DETALLE_SUCURSAL_OFICINA)
        MyBase.AddObject("DETALLE_SUCURSAL_OFICINA", dETALLE_SUCURSAL_OFICINA)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet GESTIONES. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToGESTIONES(ByVal gESTIONES As GESTIONES)
        MyBase.AddObject("GESTIONES", gESTIONES)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet MUNICIPIOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToMUNICIPIOS(ByVal mUNICIPIOS As MUNICIPIOS)
        MyBase.AddObject("MUNICIPIOS", mUNICIPIOS)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet OFICINAS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToOFICINAS(ByVal oFICINAS As OFICINAS)
        MyBase.AddObject("OFICINAS", oFICINAS)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet PERFILES. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToPERFILES(ByVal pERFILES As PERFILES)
        MyBase.AddObject("PERFILES", pERFILES)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet PETICION_GESTIONES. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToPETICION_GESTIONES(ByVal pETICION_GESTIONES As PETICION_GESTIONES)
        MyBase.AddObject("PETICION_GESTIONES", pETICION_GESTIONES)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet SUCURSALES. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToSUCURSALES(ByVal sUCURSALES As SUCURSALES)
        MyBase.AddObject("SUCURSALES", sUCURSALES)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet USUARIOS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToUSUARIOS(ByVal uSUARIOS As USUARIOS)
        MyBase.AddObject("USUARIOS", uSUARIOS)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet VENTANILLAS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToVENTANILLAS(ByVal vENTANILLAS As VENTANILLAS)
        MyBase.AddObject("VENTANILLAS", vENTANILLAS)
    End Sub

    ''' <summary>
    ''' Método desusado para agregar un nuevo objeto al EntitySet DETALLE_OFICINA_GESTIONES. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet(Of T) asociada.
    ''' </summary>
    Public Sub AddToDETALLE_OFICINA_GESTIONES(ByVal dETALLE_OFICINA_GESTIONES As DETALLE_OFICINA_GESTIONES)
        MyBase.AddObject("DETALLE_OFICINA_GESTIONES", dETALLE_OFICINA_GESTIONES)
    End Sub

    #End Region

End Class

#End Region

#Region "Entidades"

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Modelo", Name:="DETALLE_OFICINA_GESTIONES")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DETALLE_OFICINA_GESTIONES
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto DETALLE_OFICINA_GESTIONES.
    ''' </summary>
    ''' <param name="iDDETALLE_OFICINA_GESTION">Valor inicial de la propiedad IDDETALLE_OFICINA_GESTION.</param>
    Public Shared Function CreateDETALLE_OFICINA_GESTIONES(iDDETALLE_OFICINA_GESTION As Global.System.Decimal) As DETALLE_OFICINA_GESTIONES
        Dim dETALLE_OFICINA_GESTIONES as DETALLE_OFICINA_GESTIONES = New DETALLE_OFICINA_GESTIONES
        dETALLE_OFICINA_GESTIONES.IDDETALLE_OFICINA_GESTION = iDDETALLE_OFICINA_GESTION
        Return dETALLE_OFICINA_GESTIONES
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_OFICINA_GESTION() As Global.System.Decimal
        Get
            Return _IDDETALLE_OFICINA_GESTION
        End Get
        Set
            If (_IDDETALLE_OFICINA_GESTION <> Value) Then
                OnIDDETALLE_OFICINA_GESTIONChanging(value)
                ReportPropertyChanging("IDDETALLE_OFICINA_GESTION")
                _IDDETALLE_OFICINA_GESTION = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDDETALLE_OFICINA_GESTION")
                OnIDDETALLE_OFICINA_GESTIONChanged()
            End If
        End Set
    End Property

    Private _IDDETALLE_OFICINA_GESTION As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_OFICINA_GESTIONChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_OFICINA_GESTIONChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDOFICINA() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDOFICINA
        End Get
        Set
            OnIDOFICINAChanging(value)
            ReportPropertyChanging("IDOFICINA")
            _IDOFICINA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDOFICINA")
            OnIDOFICINAChanged()
        End Set
    End Property

    Private _IDOFICINA As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDOFICINAChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDOFICINAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDGESTION() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDGESTION
        End Get
        Set
            OnIDGESTIONChanging(value)
            ReportPropertyChanging("IDGESTION")
            _IDGESTION = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDGESTION")
            OnIDGESTIONChanged()
        End Set
    End Property

    Private _IDGESTION As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDGESTIONChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDGESTIONChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS")>
    Public Property OFICINAS() As OFICINAS
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("Modelo.DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("Modelo.DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OFICINASReference() As EntityReference(Of OFICINAS)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("Modelo.DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of OFICINAS)("Modelo.DETALLE_OFICINA_GESTIONES_FK1", "OFICINAS", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES")>
    Public Property GESTIONES() As GESTIONES
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("Modelo.DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("Modelo.DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property GESTIONESReference() As EntityReference(Of GESTIONES)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("Modelo.DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of GESTIONES)("Modelo.DETALLE_OFICINA_GESTIONES_FK2", "GESTIONES", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "GESTIONES_VENTANILLAS1", "VENTANILLAS")>
     Public Property VENTANILLAS() As EntityCollection(Of VENTANILLAS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of VENTANILLAS)("Modelo.GESTIONES_VENTANILLAS1", "VENTANILLAS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of VENTANILLAS)("Modelo.GESTIONES_VENTANILLAS1", "VENTANILLAS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Modelo", Name:="DETALLE_SUCURSAL_OFICINA")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DETALLE_SUCURSAL_OFICINA
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto DETALLE_SUCURSAL_OFICINA.
    ''' </summary>
    ''' <param name="iDDETALLE_SUCURSAL_OFICINA">Valor inicial de la propiedad IDDETALLE_SUCURSAL_OFICINA.</param>
    Public Shared Function CreateDETALLE_SUCURSAL_OFICINA(iDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal) As DETALLE_SUCURSAL_OFICINA
        Dim dETALLE_SUCURSAL_OFICINA as DETALLE_SUCURSAL_OFICINA = New DETALLE_SUCURSAL_OFICINA
        dETALLE_SUCURSAL_OFICINA.IDDETALLE_SUCURSAL_OFICINA = iDDETALLE_SUCURSAL_OFICINA
        Return dETALLE_SUCURSAL_OFICINA
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_SUCURSAL_OFICINA() As Global.System.Decimal
        Get
            Return _IDDETALLE_SUCURSAL_OFICINA
        End Get
        Set
            If (_IDDETALLE_SUCURSAL_OFICINA <> Value) Then
                OnIDDETALLE_SUCURSAL_OFICINAChanging(value)
                ReportPropertyChanging("IDDETALLE_SUCURSAL_OFICINA")
                _IDDETALLE_SUCURSAL_OFICINA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDDETALLE_SUCURSAL_OFICINA")
                OnIDDETALLE_SUCURSAL_OFICINAChanged()
            End If
        End Set
    End Property

    Private _IDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDSUCURSAL() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDSUCURSAL
        End Get
        Set
            OnIDSUCURSALChanging(value)
            ReportPropertyChanging("IDSUCURSAL")
            _IDSUCURSAL = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDSUCURSAL")
            OnIDSUCURSALChanged()
        End Set
    End Property

    Private _IDSUCURSAL As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDSUCURSALChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDSUCURSALChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDOFICINA() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDOFICINA
        End Get
        Set
            OnIDOFICINAChanging(value)
            ReportPropertyChanging("IDOFICINA")
            _IDOFICINA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDOFICINA")
            OnIDOFICINAChanged()
        End Set
    End Property

    Private _IDOFICINA As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDOFICINAChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDOFICINAChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES")>
    Public Property SUCURSALES() As SUCURSALES
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SUCURSALES)("Modelo.DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SUCURSALES)("Modelo.DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property SUCURSALESReference() As EntityReference(Of SUCURSALES)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of SUCURSALES)("Modelo.DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of SUCURSALES)("Modelo.DETALLE_SUCURSAL_OFICINA_FK1", "SUCURSALES", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS")>
    Public Property OFICINAS() As OFICINAS
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("Modelo.DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("Modelo.DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property OFICINASReference() As EntityReference(Of OFICINAS)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of OFICINAS)("Modelo.DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of OFICINAS)("Modelo.DETALLE_SUCURSAL_OFICINA_FK2", "OFICINAS", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "USUARIOS_FK1", "USUARIOS")>
     Public Property USUARIOS() As EntityCollection(Of USUARIOS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of USUARIOS)("Modelo.USUARIOS_FK1", "USUARIOS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of USUARIOS)("Modelo.USUARIOS_FK1", "USUARIOS", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "VENTANILLAS_FK1", "VENTANILLAS")>
     Public Property VENTANILLAS() As EntityCollection(Of VENTANILLAS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of VENTANILLAS)("Modelo.VENTANILLAS_FK1", "VENTANILLAS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of VENTANILLAS)("Modelo.VENTANILLAS_FK1", "VENTANILLAS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Modelo", Name:="GESTIONES")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class GESTIONES
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto GESTIONES.
    ''' </summary>
    ''' <param name="iDGESTION">Valor inicial de la propiedad IDGESTION.</param>
    Public Shared Function CreateGESTIONES(iDGESTION As Global.System.Decimal) As GESTIONES
        Dim gESTIONES as GESTIONES = New GESTIONES
        gESTIONES.IDGESTION = iDGESTION
        Return gESTIONES
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDGESTION() As Global.System.Decimal
        Get
            Return _IDGESTION
        End Get
        Set
            If (_IDGESTION <> Value) Then
                OnIDGESTIONChanging(value)
                ReportPropertyChanging("IDGESTION")
                _IDGESTION = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDGESTION")
                OnIDGESTIONChanged()
            End If
        End Set
    End Property

    Private _IDGESTION As Global.System.Decimal
    Private Partial Sub OnIDGESTIONChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDGESTIONChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CODIGO() As Global.System.String
        Get
            Return _CODIGO
        End Get
        Set
            OnCODIGOChanging(value)
            ReportPropertyChanging("CODIGO")
            _CODIGO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CODIGO")
            OnCODIGOChanged()
        End Set
    End Property

    Private _CODIGO As Global.System.String
    Private Partial Sub OnCODIGOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCODIGOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            OnNOMBREChanging(value)
            ReportPropertyChanging("NOMBRE")
            _NOMBRE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE")
            OnNOMBREChanged()
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property TIEMPO() As Nullable(Of Global.System.Decimal)
        Get
            Return _TIEMPO
        End Get
        Set
            OnTIEMPOChanging(value)
            ReportPropertyChanging("TIEMPO")
            _TIEMPO = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TIEMPO")
            OnTIEMPOChanged()
        End Set
    End Property

    Private _TIEMPO As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnTIEMPOChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnTIEMPOChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "PETICION_GESTIONES_FK1", "PETICION_GESTIONES")>
     Public Property PETICION_GESTIONES() As EntityCollection(Of PETICION_GESTIONES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of PETICION_GESTIONES)("Modelo.PETICION_GESTIONES_FK1", "PETICION_GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of PETICION_GESTIONES)("Modelo.PETICION_GESTIONES_FK1", "PETICION_GESTIONES", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "DETALLE_OFICINA_GESTIONES_FK2", "DETALLE_OFICINA_GESTIONES")>
     Public Property DETALLE_OFICINA_GESTIONES() As EntityCollection(Of DETALLE_OFICINA_GESTIONES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("Modelo.DETALLE_OFICINA_GESTIONES_FK2", "DETALLE_OFICINA_GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("Modelo.DETALLE_OFICINA_GESTIONES_FK2", "DETALLE_OFICINA_GESTIONES", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Modelo", Name:="MUNICIPIOS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class MUNICIPIOS
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto MUNICIPIOS.
    ''' </summary>
    ''' <param name="iDMUNICIPIO">Valor inicial de la propiedad IDMUNICIPIO.</param>
    Public Shared Function CreateMUNICIPIOS(iDMUNICIPIO As Global.System.Decimal) As MUNICIPIOS
        Dim mUNICIPIOS as MUNICIPIOS = New MUNICIPIOS
        mUNICIPIOS.IDMUNICIPIO = iDMUNICIPIO
        Return mUNICIPIOS
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDMUNICIPIO() As Global.System.Decimal
        Get
            Return _IDMUNICIPIO
        End Get
        Set
            If (_IDMUNICIPIO <> Value) Then
                OnIDMUNICIPIOChanging(value)
                ReportPropertyChanging("IDMUNICIPIO")
                _IDMUNICIPIO = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDMUNICIPIO")
                OnIDMUNICIPIOChanged()
            End If
        End Set
    End Property

    Private _IDMUNICIPIO As Global.System.Decimal
    Private Partial Sub OnIDMUNICIPIOChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDMUNICIPIOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDDEPARTAMENTO() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDDEPARTAMENTO
        End Get
        Set
            OnIDDEPARTAMENTOChanging(value)
            ReportPropertyChanging("IDDEPARTAMENTO")
            _IDDEPARTAMENTO = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDDEPARTAMENTO")
            OnIDDEPARTAMENTOChanged()
        End Set
    End Property

    Private _IDDEPARTAMENTO As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDDEPARTAMENTOChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDDEPARTAMENTOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CODIGO_MPIO() As Global.System.String
        Get
            Return _CODIGO_MPIO
        End Get
        Set
            OnCODIGO_MPIOChanging(value)
            ReportPropertyChanging("CODIGO_MPIO")
            _CODIGO_MPIO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CODIGO_MPIO")
            OnCODIGO_MPIOChanged()
        End Set
    End Property

    Private _CODIGO_MPIO As Global.System.String
    Private Partial Sub OnCODIGO_MPIOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCODIGO_MPIOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE_MPIO() As Global.System.String
        Get
            Return _NOMBRE_MPIO
        End Get
        Set
            OnNOMBRE_MPIOChanging(value)
            ReportPropertyChanging("NOMBRE_MPIO")
            _NOMBRE_MPIO = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE_MPIO")
            OnNOMBRE_MPIOChanged()
        End Set
    End Property

    Private _NOMBRE_MPIO As Global.System.String
    Private Partial Sub OnNOMBRE_MPIOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_MPIOChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "SUCURSALES_FK1", "SUCURSALES")>
     Public Property SUCURSALES() As EntityCollection(Of SUCURSALES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of SUCURSALES)("Modelo.SUCURSALES_FK1", "SUCURSALES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of SUCURSALES)("Modelo.SUCURSALES_FK1", "SUCURSALES", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Modelo", Name:="OFICINAS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class OFICINAS
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto OFICINAS.
    ''' </summary>
    ''' <param name="iDOFICINA">Valor inicial de la propiedad IDOFICINA.</param>
    Public Shared Function CreateOFICINAS(iDOFICINA As Global.System.Decimal) As OFICINAS
        Dim oFICINAS as OFICINAS = New OFICINAS
        oFICINAS.IDOFICINA = iDOFICINA
        Return oFICINAS
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDOFICINA() As Global.System.Decimal
        Get
            Return _IDOFICINA
        End Get
        Set
            If (_IDOFICINA <> Value) Then
                OnIDOFICINAChanging(value)
                ReportPropertyChanging("IDOFICINA")
                _IDOFICINA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDOFICINA")
                OnIDOFICINAChanged()
            End If
        End Set
    End Property

    Private _IDOFICINA As Global.System.Decimal
    Private Partial Sub OnIDOFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDOFICINAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE_OFICINA() As Global.System.String
        Get
            Return _NOMBRE_OFICINA
        End Get
        Set
            OnNOMBRE_OFICINAChanging(value)
            ReportPropertyChanging("NOMBRE_OFICINA")
            _NOMBRE_OFICINA = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE_OFICINA")
            OnNOMBRE_OFICINAChanged()
        End Set
    End Property

    Private _NOMBRE_OFICINA As Global.System.String
    Private Partial Sub OnNOMBRE_OFICINAChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_OFICINAChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "DETALLE_SUCURSAL_OFICINA_FK2", "DETALLE_SUCURSAL_OFICINA")>
     Public Property DETALLE_SUCURSAL_OFICINA() As EntityCollection(Of DETALLE_SUCURSAL_OFICINA)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DETALLE_SUCURSAL_OFICINA)("Modelo.DETALLE_SUCURSAL_OFICINA_FK2", "DETALLE_SUCURSAL_OFICINA")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DETALLE_SUCURSAL_OFICINA)("Modelo.DETALLE_SUCURSAL_OFICINA_FK2", "DETALLE_SUCURSAL_OFICINA", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "DETALLE_OFICINA_GESTIONES_FK1", "DETALLE_OFICINA_GESTIONES")>
     Public Property DETALLE_OFICINA_GESTIONES() As EntityCollection(Of DETALLE_OFICINA_GESTIONES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("Modelo.DETALLE_OFICINA_GESTIONES_FK1", "DETALLE_OFICINA_GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("Modelo.DETALLE_OFICINA_GESTIONES_FK1", "DETALLE_OFICINA_GESTIONES", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Modelo", Name:="PERFILES")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class PERFILES
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto PERFILES.
    ''' </summary>
    ''' <param name="iDPERFIL">Valor inicial de la propiedad IDPERFIL.</param>
    Public Shared Function CreatePERFILES(iDPERFIL As Global.System.Decimal) As PERFILES
        Dim pERFILES as PERFILES = New PERFILES
        pERFILES.IDPERFIL = iDPERFIL
        Return pERFILES
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDPERFIL() As Global.System.Decimal
        Get
            Return _IDPERFIL
        End Get
        Set
            If (_IDPERFIL <> Value) Then
                OnIDPERFILChanging(value)
                ReportPropertyChanging("IDPERFIL")
                _IDPERFIL = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDPERFIL")
                OnIDPERFILChanged()
            End If
        End Set
    End Property

    Private _IDPERFIL As Global.System.Decimal
    Private Partial Sub OnIDPERFILChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDPERFILChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE_PERFIL() As Global.System.String
        Get
            Return _NOMBRE_PERFIL
        End Get
        Set
            OnNOMBRE_PERFILChanging(value)
            ReportPropertyChanging("NOMBRE_PERFIL")
            _NOMBRE_PERFIL = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE_PERFIL")
            OnNOMBRE_PERFILChanged()
        End Set
    End Property

    Private _NOMBRE_PERFIL As Global.System.String
    Private Partial Sub OnNOMBRE_PERFILChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBRE_PERFILChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "DETALLE_USUARIOS_PERFILES", "USUARIOS")>
     Public Property USUARIOS() As EntityCollection(Of USUARIOS)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of USUARIOS)("Modelo.DETALLE_USUARIOS_PERFILES", "USUARIOS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of USUARIOS)("Modelo.DETALLE_USUARIOS_PERFILES", "USUARIOS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Modelo", Name:="PETICION_GESTIONES")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class PETICION_GESTIONES
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto PETICION_GESTIONES.
    ''' </summary>
    ''' <param name="iDPETICION">Valor inicial de la propiedad IDPETICION.</param>
    ''' <param name="iDGESTION">Valor inicial de la propiedad IDGESTION.</param>
    ''' <param name="iDDETALLE_SUCURSAL_OFICINA">Valor inicial de la propiedad IDDETALLE_SUCURSAL_OFICINA.</param>
    ''' <param name="fECHAHORA_PETICION">Valor inicial de la propiedad FECHAHORA_PETICION.</param>
    ''' <param name="pENDIENTE">Valor inicial de la propiedad PENDIENTE.</param>
    ''' <param name="tERCERAEDAD">Valor inicial de la propiedad TERCERAEDAD.</param>
    ''' <param name="aTENDIDO">Valor inicial de la propiedad ATENDIDO.</param>
    ''' <param name="eNESPERA">Valor inicial de la propiedad ENESPERA.</param>
    Public Shared Function CreatePETICION_GESTIONES(iDPETICION As Global.System.Decimal, iDGESTION As Global.System.Decimal, iDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal, fECHAHORA_PETICION As Global.System.DateTime, pENDIENTE As Global.System.Decimal, tERCERAEDAD As Global.System.Decimal, aTENDIDO As Global.System.Decimal, eNESPERA As Global.System.Decimal) As PETICION_GESTIONES
        Dim pETICION_GESTIONES as PETICION_GESTIONES = New PETICION_GESTIONES
        pETICION_GESTIONES.IDPETICION = iDPETICION
        pETICION_GESTIONES.IDGESTION = iDGESTION
        pETICION_GESTIONES.IDDETALLE_SUCURSAL_OFICINA = iDDETALLE_SUCURSAL_OFICINA
        pETICION_GESTIONES.FECHAHORA_PETICION = fECHAHORA_PETICION
        pETICION_GESTIONES.PENDIENTE = pENDIENTE
        pETICION_GESTIONES.TERCERAEDAD = tERCERAEDAD
        pETICION_GESTIONES.ATENDIDO = aTENDIDO
        pETICION_GESTIONES.ENESPERA = eNESPERA
        Return pETICION_GESTIONES
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDPETICION() As Global.System.Decimal
        Get
            Return _IDPETICION
        End Get
        Set
            If (_IDPETICION <> Value) Then
                OnIDPETICIONChanging(value)
                ReportPropertyChanging("IDPETICION")
                _IDPETICION = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDPETICION")
                OnIDPETICIONChanged()
            End If
        End Set
    End Property

    Private _IDPETICION As Global.System.Decimal
    Private Partial Sub OnIDPETICIONChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDPETICIONChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDGESTION() As Global.System.Decimal
        Get
            Return _IDGESTION
        End Get
        Set
            OnIDGESTIONChanging(value)
            ReportPropertyChanging("IDGESTION")
            _IDGESTION = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDGESTION")
            OnIDGESTIONChanged()
        End Set
    End Property

    Private _IDGESTION As Global.System.Decimal
    Private Partial Sub OnIDGESTIONChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDGESTIONChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_SUCURSAL_OFICINA() As Global.System.Decimal
        Get
            Return _IDDETALLE_SUCURSAL_OFICINA
        End Get
        Set
            OnIDDETALLE_SUCURSAL_OFICINAChanging(value)
            ReportPropertyChanging("IDDETALLE_SUCURSAL_OFICINA")
            _IDDETALLE_SUCURSAL_OFICINA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDDETALLE_SUCURSAL_OFICINA")
            OnIDDETALLE_SUCURSAL_OFICINAChanged()
        End Set
    End Property

    Private _IDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property FECHAHORA_PETICION() As Global.System.DateTime
        Get
            Return _FECHAHORA_PETICION
        End Get
        Set
            OnFECHAHORA_PETICIONChanging(value)
            ReportPropertyChanging("FECHAHORA_PETICION")
            _FECHAHORA_PETICION = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FECHAHORA_PETICION")
            OnFECHAHORA_PETICIONChanged()
        End Set
    End Property

    Private _FECHAHORA_PETICION As Global.System.DateTime
    Private Partial Sub OnFECHAHORA_PETICIONChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnFECHAHORA_PETICIONChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FECHAHORA_ATENCION() As Nullable(Of Global.System.DateTime)
        Get
            Return _FECHAHORA_ATENCION
        End Get
        Set
            OnFECHAHORA_ATENCIONChanging(value)
            ReportPropertyChanging("FECHAHORA_ATENCION")
            _FECHAHORA_ATENCION = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FECHAHORA_ATENCION")
            OnFECHAHORA_ATENCIONChanged()
        End Set
    End Property

    Private _FECHAHORA_ATENCION As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnFECHAHORA_ATENCIONChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnFECHAHORA_ATENCIONChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property FECHAHORA_FINALIZAR() As Nullable(Of Global.System.DateTime)
        Get
            Return _FECHAHORA_FINALIZAR
        End Get
        Set
            OnFECHAHORA_FINALIZARChanging(value)
            ReportPropertyChanging("FECHAHORA_FINALIZAR")
            _FECHAHORA_FINALIZAR = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("FECHAHORA_FINALIZAR")
            OnFECHAHORA_FINALIZARChanged()
        End Set
    End Property

    Private _FECHAHORA_FINALIZAR As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnFECHAHORA_FINALIZARChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnFECHAHORA_FINALIZARChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property SECUENCIA() As Nullable(Of Global.System.Decimal)
        Get
            Return _SECUENCIA
        End Get
        Set
            OnSECUENCIAChanging(value)
            ReportPropertyChanging("SECUENCIA")
            _SECUENCIA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("SECUENCIA")
            OnSECUENCIAChanged()
        End Set
    End Property

    Private _SECUENCIA As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnSECUENCIAChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnSECUENCIAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PENDIENTE() As Global.System.Decimal
        Get
            Return _PENDIENTE
        End Get
        Set
            OnPENDIENTEChanging(value)
            ReportPropertyChanging("PENDIENTE")
            _PENDIENTE = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PENDIENTE")
            OnPENDIENTEChanged()
        End Set
    End Property

    Private _PENDIENTE As Global.System.Decimal
    Private Partial Sub OnPENDIENTEChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnPENDIENTEChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TERCERAEDAD() As Global.System.Decimal
        Get
            Return _TERCERAEDAD
        End Get
        Set
            OnTERCERAEDADChanging(value)
            ReportPropertyChanging("TERCERAEDAD")
            _TERCERAEDAD = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("TERCERAEDAD")
            OnTERCERAEDADChanged()
        End Set
    End Property

    Private _TERCERAEDAD As Global.System.Decimal
    Private Partial Sub OnTERCERAEDADChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnTERCERAEDADChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ATENDIDO() As Global.System.Decimal
        Get
            Return _ATENDIDO
        End Get
        Set
            OnATENDIDOChanging(value)
            ReportPropertyChanging("ATENDIDO")
            _ATENDIDO = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ATENDIDO")
            OnATENDIDOChanged()
        End Set
    End Property

    Private _ATENDIDO As Global.System.Decimal
    Private Partial Sub OnATENDIDOChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnATENDIDOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property ENESPERA() As Global.System.Decimal
        Get
            Return _ENESPERA
        End Get
        Set
            OnENESPERAChanging(value)
            ReportPropertyChanging("ENESPERA")
            _ENESPERA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ENESPERA")
            OnENESPERAChanged()
        End Set
    End Property

    Private _ENESPERA As Global.System.Decimal
    Private Partial Sub OnENESPERAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnENESPERAChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "PETICION_GESTIONES_FK1", "GESTIONES")>
    Public Property GESTIONES() As GESTIONES
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("Modelo.PETICION_GESTIONES_FK1", "GESTIONES").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("Modelo.PETICION_GESTIONES_FK1", "GESTIONES").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property GESTIONESReference() As EntityReference(Of GESTIONES)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of GESTIONES)("Modelo.PETICION_GESTIONES_FK1", "GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of GESTIONES)("Modelo.PETICION_GESTIONES_FK1", "GESTIONES", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Modelo", Name:="SUCURSALES")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class SUCURSALES
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto SUCURSALES.
    ''' </summary>
    ''' <param name="iDSUCURSAL">Valor inicial de la propiedad IDSUCURSAL.</param>
    ''' <param name="iDEMPRESA">Valor inicial de la propiedad IDEMPRESA.</param>
    ''' <param name="nOMBRE">Valor inicial de la propiedad NOMBRE.</param>
    ''' <param name="dIRECCION">Valor inicial de la propiedad DIRECCION.</param>
    ''' <param name="iDMUNICIPIO">Valor inicial de la propiedad IDMUNICIPIO.</param>
    Public Shared Function CreateSUCURSALES(iDSUCURSAL As Global.System.Decimal, iDEMPRESA As Global.System.Decimal, nOMBRE As Global.System.String, dIRECCION As Global.System.String, iDMUNICIPIO As Global.System.Decimal) As SUCURSALES
        Dim sUCURSALES as SUCURSALES = New SUCURSALES
        sUCURSALES.IDSUCURSAL = iDSUCURSAL
        sUCURSALES.IDEMPRESA = iDEMPRESA
        sUCURSALES.NOMBRE = nOMBRE
        sUCURSALES.DIRECCION = dIRECCION
        sUCURSALES.IDMUNICIPIO = iDMUNICIPIO
        Return sUCURSALES
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDSUCURSAL() As Global.System.Decimal
        Get
            Return _IDSUCURSAL
        End Get
        Set
            If (_IDSUCURSAL <> Value) Then
                OnIDSUCURSALChanging(value)
                ReportPropertyChanging("IDSUCURSAL")
                _IDSUCURSAL = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDSUCURSAL")
                OnIDSUCURSALChanged()
            End If
        End Set
    End Property

    Private _IDSUCURSAL As Global.System.Decimal
    Private Partial Sub OnIDSUCURSALChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDSUCURSALChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDEMPRESA() As Global.System.Decimal
        Get
            Return _IDEMPRESA
        End Get
        Set
            OnIDEMPRESAChanging(value)
            ReportPropertyChanging("IDEMPRESA")
            _IDEMPRESA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDEMPRESA")
            OnIDEMPRESAChanged()
        End Set
    End Property

    Private _IDEMPRESA As Global.System.Decimal
    Private Partial Sub OnIDEMPRESAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDEMPRESAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            OnNOMBREChanging(value)
            ReportPropertyChanging("NOMBRE")
            _NOMBRE = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("NOMBRE")
            OnNOMBREChanged()
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DIRECCION() As Global.System.String
        Get
            Return _DIRECCION
        End Get
        Set
            OnDIRECCIONChanging(value)
            ReportPropertyChanging("DIRECCION")
            _DIRECCION = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("DIRECCION")
            OnDIRECCIONChanged()
        End Set
    End Property

    Private _DIRECCION As Global.System.String
    Private Partial Sub OnDIRECCIONChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDIRECCIONChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDMUNICIPIO() As Global.System.Decimal
        Get
            Return _IDMUNICIPIO
        End Get
        Set
            OnIDMUNICIPIOChanging(value)
            ReportPropertyChanging("IDMUNICIPIO")
            _IDMUNICIPIO = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDMUNICIPIO")
            OnIDMUNICIPIOChanged()
        End Set
    End Property

    Private _IDMUNICIPIO As Global.System.Decimal
    Private Partial Sub OnIDMUNICIPIOChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDMUNICIPIOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LATITUD() As Nullable(Of Global.System.Decimal)
        Get
            Return _LATITUD
        End Get
        Set
            OnLATITUDChanging(value)
            ReportPropertyChanging("LATITUD")
            _LATITUD = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LATITUD")
            OnLATITUDChanged()
        End Set
    End Property

    Private _LATITUD As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnLATITUDChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnLATITUDChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LONGITUD() As Nullable(Of Global.System.Decimal)
        Get
            Return _LONGITUD
        End Get
        Set
            OnLONGITUDChanging(value)
            ReportPropertyChanging("LONGITUD")
            _LONGITUD = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LONGITUD")
            OnLONGITUDChanged()
        End Set
    End Property

    Private _LONGITUD As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnLONGITUDChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnLONGITUDChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "DETALLE_SUCURSAL_OFICINA_FK1", "DETALLE_SUCURSAL_OFICINA")>
     Public Property DETALLE_SUCURSAL_OFICINA() As EntityCollection(Of DETALLE_SUCURSAL_OFICINA)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DETALLE_SUCURSAL_OFICINA)("Modelo.DETALLE_SUCURSAL_OFICINA_FK1", "DETALLE_SUCURSAL_OFICINA")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DETALLE_SUCURSAL_OFICINA)("Modelo.DETALLE_SUCURSAL_OFICINA_FK1", "DETALLE_SUCURSAL_OFICINA", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "SUCURSALES_FK1", "MUNICIPIOS")>
    Public Property MUNICIPIOS() As MUNICIPIOS
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MUNICIPIOS)("Modelo.SUCURSALES_FK1", "MUNICIPIOS").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MUNICIPIOS)("Modelo.SUCURSALES_FK1", "MUNICIPIOS").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property MUNICIPIOSReference() As EntityReference(Of MUNICIPIOS)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of MUNICIPIOS)("Modelo.SUCURSALES_FK1", "MUNICIPIOS")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of MUNICIPIOS)("Modelo.SUCURSALES_FK1", "MUNICIPIOS", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Modelo", Name:="USUARIOS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class USUARIOS
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto USUARIOS.
    ''' </summary>
    ''' <param name="iDUSUARIO">Valor inicial de la propiedad IDUSUARIO.</param>
    ''' <param name="uSUARIO">Valor inicial de la propiedad USUARIO.</param>
    Public Shared Function CreateUSUARIOS(iDUSUARIO As Global.System.Decimal, uSUARIO As Global.System.String) As USUARIOS
        Dim uSUARIOS as USUARIOS = New USUARIOS
        uSUARIOS.IDUSUARIO = iDUSUARIO
        uSUARIOS.USUARIO = uSUARIO
        Return uSUARIOS
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDUSUARIO() As Global.System.Decimal
        Get
            Return _IDUSUARIO
        End Get
        Set
            If (_IDUSUARIO <> Value) Then
                OnIDUSUARIOChanging(value)
                ReportPropertyChanging("IDUSUARIO")
                _IDUSUARIO = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDUSUARIO")
                OnIDUSUARIOChanged()
            End If
        End Set
    End Property

    Private _IDUSUARIO As Global.System.Decimal
    Private Partial Sub OnIDUSUARIOChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDUSUARIOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property USUARIO() As Global.System.String
        Get
            Return _USUARIO
        End Get
        Set
            OnUSUARIOChanging(value)
            ReportPropertyChanging("USUARIO")
            _USUARIO = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("USUARIO")
            OnUSUARIOChanged()
        End Set
    End Property

    Private _USUARIO As Global.System.String
    Private Partial Sub OnUSUARIOChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnUSUARIOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property CONTRASENA() As Global.System.String
        Get
            Return _CONTRASENA
        End Get
        Set
            OnCONTRASENAChanging(value)
            ReportPropertyChanging("CONTRASENA")
            _CONTRASENA = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("CONTRASENA")
            OnCONTRASENAChanged()
        End Set
    End Property

    Private _CONTRASENA As Global.System.String
    Private Partial Sub OnCONTRASENAChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCONTRASENAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property NOMBRE() As Global.System.String
        Get
            Return _NOMBRE
        End Get
        Set
            OnNOMBREChanging(value)
            ReportPropertyChanging("NOMBRE")
            _NOMBRE = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("NOMBRE")
            OnNOMBREChanged()
        End Set
    End Property

    Private _NOMBRE As Global.System.String
    Private Partial Sub OnNOMBREChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNOMBREChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property APELLIDOS() As Global.System.String
        Get
            Return _APELLIDOS
        End Get
        Set
            OnAPELLIDOSChanging(value)
            ReportPropertyChanging("APELLIDOS")
            _APELLIDOS = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("APELLIDOS")
            OnAPELLIDOSChanged()
        End Set
    End Property

    Private _APELLIDOS As Global.System.String
    Private Partial Sub OnAPELLIDOSChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAPELLIDOSChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property ESTADO() As Nullable(Of Global.System.Decimal)
        Get
            Return _ESTADO
        End Get
        Set
            OnESTADOChanging(value)
            ReportPropertyChanging("ESTADO")
            _ESTADO = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("ESTADO")
            OnESTADOChanged()
        End Set
    End Property

    Private _ESTADO As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnESTADOChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnESTADOChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_SUCURSAL_OFICINA() As Nullable(Of Global.System.Decimal)
        Get
            Return _IDDETALLE_SUCURSAL_OFICINA
        End Get
        Set
            OnIDDETALLE_SUCURSAL_OFICINAChanging(value)
            ReportPropertyChanging("IDDETALLE_SUCURSAL_OFICINA")
            _IDDETALLE_SUCURSAL_OFICINA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDDETALLE_SUCURSAL_OFICINA")
            OnIDDETALLE_SUCURSAL_OFICINAChanged()
        End Set
    End Property

    Private _IDDETALLE_SUCURSAL_OFICINA As Nullable(Of Global.System.Decimal)
    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanging(value As Nullable(Of Global.System.Decimal))
    End Sub

    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA")>
    Public Property DETALLE_SUCURSAL_OFICINA() As DETALLE_SUCURSAL_OFICINA
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("Modelo.USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("Modelo.USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property DETALLE_SUCURSAL_OFICINAReference() As EntityReference(Of DETALLE_SUCURSAL_OFICINA)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("Modelo.USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("Modelo.USUARIOS_FK1", "DETALLE_SUCURSAL_OFICINA", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "DETALLE_USUARIOS_PERFILES", "PERFILES")>
     Public Property PERFILES() As EntityCollection(Of PERFILES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of PERFILES)("Modelo.DETALLE_USUARIOS_PERFILES", "PERFILES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of PERFILES)("Modelo.DETALLE_USUARIOS_PERFILES", "PERFILES", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No hay documentación de metadatos disponible.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="Modelo", Name:="VENTANILLAS")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class VENTANILLAS
    Inherits EntityObject
    #Region "Método de generador"

    ''' <summary>
    ''' Crear un nuevo objeto VENTANILLAS.
    ''' </summary>
    ''' <param name="iDVENTANILLA">Valor inicial de la propiedad IDVENTANILLA.</param>
    ''' <param name="iDDETALLE_SUCURSAL_OFICINA">Valor inicial de la propiedad IDDETALLE_SUCURSAL_OFICINA.</param>
    ''' <param name="nUMERO_VENTANILLA">Valor inicial de la propiedad NUMERO_VENTANILLA.</param>
    Public Shared Function CreateVENTANILLAS(iDVENTANILLA As Global.System.Decimal, iDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal, nUMERO_VENTANILLA As Global.System.Decimal) As VENTANILLAS
        Dim vENTANILLAS as VENTANILLAS = New VENTANILLAS
        vENTANILLAS.IDVENTANILLA = iDVENTANILLA
        vENTANILLAS.IDDETALLE_SUCURSAL_OFICINA = iDDETALLE_SUCURSAL_OFICINA
        vENTANILLAS.NUMERO_VENTANILLA = nUMERO_VENTANILLA
        Return vENTANILLAS
    End Function

    #End Region

    #Region "Propiedades primitivas"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDVENTANILLA() As Global.System.Decimal
        Get
            Return _IDVENTANILLA
        End Get
        Set
            If (_IDVENTANILLA <> Value) Then
                OnIDVENTANILLAChanging(value)
                ReportPropertyChanging("IDVENTANILLA")
                _IDVENTANILLA = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDVENTANILLA")
                OnIDVENTANILLAChanged()
            End If
        End Set
    End Property

    Private _IDVENTANILLA As Global.System.Decimal
    Private Partial Sub OnIDVENTANILLAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDVENTANILLAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDDETALLE_SUCURSAL_OFICINA() As Global.System.Decimal
        Get
            Return _IDDETALLE_SUCURSAL_OFICINA
        End Get
        Set
            OnIDDETALLE_SUCURSAL_OFICINAChanging(value)
            ReportPropertyChanging("IDDETALLE_SUCURSAL_OFICINA")
            _IDDETALLE_SUCURSAL_OFICINA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("IDDETALLE_SUCURSAL_OFICINA")
            OnIDDETALLE_SUCURSAL_OFICINAChanged()
        End Set
    End Property

    Private _IDDETALLE_SUCURSAL_OFICINA As Global.System.Decimal
    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnIDDETALLE_SUCURSAL_OFICINAChanged()
    End Sub

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property NUMERO_VENTANILLA() As Global.System.Decimal
        Get
            Return _NUMERO_VENTANILLA
        End Get
        Set
            OnNUMERO_VENTANILLAChanging(value)
            ReportPropertyChanging("NUMERO_VENTANILLA")
            _NUMERO_VENTANILLA = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("NUMERO_VENTANILLA")
            OnNUMERO_VENTANILLAChanged()
        End Set
    End Property

    Private _NUMERO_VENTANILLA As Global.System.Decimal
    Private Partial Sub OnNUMERO_VENTANILLAChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnNUMERO_VENTANILLAChanged()
    End Sub

    #End Region

    #Region "Propiedades de navegación"

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA")>
    Public Property DETALLE_SUCURSAL_OFICINA() As DETALLE_SUCURSAL_OFICINA
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("Modelo.VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("Modelo.VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property DETALLE_SUCURSAL_OFICINAReference() As EntityReference(Of DETALLE_SUCURSAL_OFICINA)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("Modelo.VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of DETALLE_SUCURSAL_OFICINA)("Modelo.VENTANILLAS_FK1", "DETALLE_SUCURSAL_OFICINA", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No hay documentación de metadatos disponible.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("Modelo", "GESTIONES_VENTANILLAS1", "DETALLE_OFICINA_GESTIONES")>
     Public Property DETALLE_OFICINA_GESTIONES() As EntityCollection(Of DETALLE_OFICINA_GESTIONES)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("Modelo.GESTIONES_VENTANILLAS1", "DETALLE_OFICINA_GESTIONES")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of DETALLE_OFICINA_GESTIONES)("Modelo.GESTIONES_VENTANILLAS1", "DETALLE_OFICINA_GESTIONES", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


